// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package go_micro_openbank_account_arv

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
	CreatedTime          uint64   `protobuf:"varint,4,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime          uint64   `protobuf:"varint,5,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *User) GetCreatedTime() uint64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *User) GetUpdatedTime() uint64 {
	if m != nil {
		return m.UpdatedTime
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string   `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Request struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserPwd              string   `protobuf:"bytes,3,opt,name=userPwd,proto3" json:"userPwd,omitempty"`
	Idfile               []byte   `protobuf:"bytes,4,opt,name=idfile,proto3" json:"idfile,omitempty"`
	Flag                 string   `protobuf:"bytes,5,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Request) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Request) GetUserPwd() string {
	if m != nil {
		return m.UserPwd
	}
	return ""
}

func (m *Request) GetIdfile() []byte {
	if m != nil {
		return m.Idfile
	}
	return nil
}

func (m *Request) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.openbank.account.arv.user")
	proto.RegisterType((*Error)(nil), "go.micro.openbank.account.arv.Error")
	proto.RegisterType((*Request)(nil), "go.micro.openbank.account.arv.Request")
	proto.RegisterType((*Response)(nil), "go.micro.openbank.account.arv.Response")
}

func init() {
	proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0)
}

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xbb, 0x4e, 0xc3, 0x40,
	0x10, 0xe4, 0x12, 0x3b, 0x8f, 0x0d, 0x2f, 0x5d, 0x81, 0xac, 0x48, 0x48, 0x96, 0x41, 0x90, 0xca,
	0x45, 0x52, 0x20, 0xd1, 0xf1, 0x2a, 0x68, 0x10, 0x9c, 0xa0, 0x46, 0x8e, 0x6f, 0x13, 0x9d, 0x48,
	0x7c, 0xe6, 0xce, 0x06, 0xa5, 0x43, 0xe2, 0x2b, 0xf8, 0x2b, 0x3e, 0x09, 0xdd, 0xda, 0x09, 0xa9,
	0x48, 0x45, 0x37, 0x73, 0x9e, 0xdd, 0x9d, 0xd9, 0x35, 0xec, 0x24, 0x69, 0xaa, 0xcb, 0xac, 0x88,
	0x73, 0xa3, 0x0b, 0xcd, 0x0f, 0xa7, 0x3a, 0x9e, 0xab, 0xd4, 0xe8, 0x58, 0xe7, 0x98, 0x8d, 0x93,
	0xec, 0x25, 0x5e, 0x0a, 0x12, 0xf3, 0x16, 0x7d, 0x30, 0xf0, 0x4a, 0x8b, 0x86, 0xef, 0x42, 0x43,
	0xc9, 0x80, 0x85, 0x6c, 0xd0, 0x14, 0x0d, 0x25, 0x39, 0x07, 0x2f, 0x4b, 0xe6, 0x18, 0x34, 0x42,
	0x36, 0xe8, 0x0a, 0xc2, 0x7c, 0x1f, 0x9a, 0xf9, 0xbb, 0x0c, 0x9a, 0xf4, 0xe4, 0x20, 0x0f, 0xa1,
	0x97, 0x1a, 0x4c, 0x0a, 0x94, 0x8f, 0x6a, 0x8e, 0x81, 0x17, 0xb2, 0x81, 0x27, 0xd6, 0x9f, 0x9c,
	0xa2, 0xcc, 0xe5, 0x4a, 0xe1, 0x57, 0x8a, 0xb5, 0xa7, 0x68, 0x04, 0xfe, 0x8d, 0x31, 0xda, 0xb8,
	0x91, 0xa9, 0x96, 0x48, 0x26, 0x7c, 0x41, 0x98, 0x1f, 0x40, 0x4b, 0x62, 0x91, 0xa8, 0x59, 0x6d,
	0xa4, 0x66, 0xd1, 0x27, 0x83, 0xb6, 0xc0, 0xd7, 0x12, 0x6d, 0xe1, 0x34, 0x2e, 0xc2, 0xed, 0x35,
	0x55, 0x76, 0x45, 0xcd, 0x78, 0x1f, 0x3a, 0x0e, 0xdd, 0xfd, 0xc6, 0x58, 0x71, 0x1e, 0x40, 0xdb,
	0xe1, 0xfb, 0x55, 0x9c, 0x25, 0x75, 0xdd, 0x94, 0x9c, 0xa8, 0x59, 0x95, 0x66, 0x5b, 0xd4, 0xcc,
	0xb9, 0x9b, 0xcc, 0x92, 0x29, 0x25, 0xe8, 0x0a, 0xc2, 0xd1, 0x17, 0x83, 0x8e, 0x40, 0x9b, 0xeb,
	0xcc, 0x52, 0x4b, 0x5b, 0xa6, 0x29, 0x5a, 0x4b, 0x3e, 0x3a, 0x62, 0x49, 0xf9, 0x39, 0xf8, 0xe8,
	0x12, 0x92, 0x8b, 0xde, 0xf0, 0x38, 0xfe, 0xf3, 0x26, 0x31, 0x6d, 0x43, 0x54, 0x25, 0xfc, 0xac,
	0xba, 0x0f, 0xb9, 0xec, 0x0d, 0x8f, 0x36, 0x94, 0x3a, 0xa9, 0xa0, 0x82, 0xe1, 0x37, 0x83, 0xf6,
	0x45, 0xf5, 0x89, 0x4b, 0xd8, 0x7b, 0x28, 0xd1, 0x2c, 0x9e, 0x2c, 0x9a, 0xcb, 0x05, 0x2d, 0xe0,
	0x64, 0x43, 0xa7, 0x7a, 0xb9, 0xfd, 0xd3, 0x8d, 0xba, 0x2a, 0x7e, 0xb4, 0xc5, 0x9f, 0x01, 0xae,
	0xe8, 0xf2, 0x6e, 0xcc, 0x3f, 0x0c, 0x18, 0xb7, 0xe8, 0x97, 0x1e, 0xfd, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x05, 0x8f, 0xc3, 0x8c, 0xe3, 0x02, 0x00, 0x00,
}
